name: commitlint
on:
  workflow_call:
    inputs:
      ref:
        description: Ref of avi2d/checks to lint with
        type: string
        default: main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/checkout@v4
        with:
          repository: avi2d/checks
          ref: ${{ inputs.ref }}
          path: checks
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
        working-directory: checks
      - run: ./checks/node_modules/.bin/commitlint --config ./checks/commitlint.config.js --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
